# Xcode build on ephemeral GitHub runner
name: build

on:
  push:
    branches: [ main, master, stage, release ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
    - name: Checkout Source
      uses: actions/checkout@v3
    - name: Build
      run: |
        xcodebuild -version
        xcodebuild -list -workspace iGoat-Swift/iGoat-Swift.xcworkspace
        xcodebuild -list -project iGoat-Swift/iGoat-Swift.xcodeproj
        pod init && pod install --project-directory iGoat-Swift/iGoat-Swift.xcodeproj
        xcodebuild -project iGoat-Swift/iGoat-Swift.xcodeproj -scheme iGoat-Swift -configuration Release build IPHONEOS_DEPLOYMENT_TARGET=16.2
