# Xcode build on ephemeral GitHub runner
name: build

on:
  push:
    branches: [ main, master, stage, release ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
    - name: Checkout Source
      uses: actions/checkout@v3
    - name: Build
      run: |
        xcodebuild -version
        xcodebuild -list -workspace iGoat-Swift/iGoat-Swift.xcworkspace
        xcodebuild -list -project iGoat-Swift/iGoat-Swift.xcodeproj
        xcodebuild -workspace iGoat-Swift/iGoat-Swift.xcworkspace -scheme iGoat-Swift build CODE_SIGNING_ALLOWED=NO IPHONEOS_DEPLOYMENT_TARGET=11.0
