# example workflow for Coverity on Polaris
name: coverity-on-polaris

on:
  push:
    branches: [ main, master, stage, release ]
  workflow_dispatch:

jobs:
  coverity-on-polaris:
    runs-on: macos-latest
    steps:
    - name: Checkout Source
      uses: actions/checkout@v3
    - name: Coverity on Polaris Scan
      env:
        POLARIS_SERVER_URL: ${{ vars.POLARIS_SERVER_URL }}
        POLARIS_ACCESS_TOKEN: ${{ secrets.POLARIS_ACCESS_TOKEN }}
        POLARIS_PROJECT: chuckaude-${{ github.event.repository.name }}
        POLARIS_ZIP: polaris_cli-macosx.zip
      run: |
        curl -fLOsS $POLARIS_SERVER_URL/api/tools/$POLARIS_ZIP
        unzip -d $RUNNER_TEMP -jo $POLARIS_ZIP && rm -f $POLARIS_ZIP
        $RUNNER_TEMP/polaris --co project.name=$POLARIS_PROJECT analyze -w
