# example workflow for Polaris SaaS scans using the Bridge CLI
name: polaris-bridge

on:
  push:
    branches: [ main, master, stage, release ]
  workflow_dispatch:

jobs:
  polaris:
    runs-on: macos-latest
    steps:
    - name: Checkout Source
      uses: actions/checkout@v3
    - name: Polaris Scan
      env:
        BRIDGE_POLARIS_SERVERURL: ${{ vars.POLARIS_SERVERURL }}
        BRIDGE_POLARIS_ACCESSTOKEN: ${{ secrets.POLARIS_ACCESSTOKEN }}
        BRIDGE_POLARIS_APPLICATION_NAME: chuckaude-${{ github.event.repository.name }}
        BRIDGE_POLARIS_PROJECT_NAME: chuckaude-${{ github.event.repository.name }}
        BRIDGECLI_MACOSX: ${{ vars.BRIDGECLI_MACOSX }}
      run: |
        curl -fLsS -o bridge.zip $BRIDGECLI_MACOSX && unzip -qo -d $RUNNER_TEMP bridge.zip && rm -f bridge.zip
        $RUNNER_TEMP/synopsys-bridge --verbose --stage polaris polaris.assessment.types=SAST,SCA
    - name: Save Logs
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: bridge-logs
        path: ${{ github.workspace }}/.bridge
